### PR TITLE
Fix 6.X version : no Custom option

### PR DESCRIPTION
**Pull request by Shnoulle**
Issue : https://github.com/tpartner/LimeSurvey-Net-Promoter-Score/issues/11

Try to have a 5+6 compatible version
**NOT** tested on 5.X with this option.

### CODE REVIEW

**Comment by tpartner** [comment]
Changing <custom_attributes> to <attributes>will break it in 3.x. In 5.x, as far as I can remember this tag was automatically changed.

I may need a new repository for 5.x and 6.x.

**Comment by Shnoulle** [comment]
> Changing <custom_attributes> to will break it in 3.x. In 5.x, as far as I can remember this tag was automatically changed.
> 
> I may need a new repository for 5.x and 6.x.

I **do not remove** `custom_attributes` , i only add `attributes` with same values.

We still have custom_attributes : https://github.com/tpartner/LimeSurvey-Net-Promoter-Score/blob/756a99077497c53a9f6220cb13c5a753bab6ef95/Net-Promoter-Score/survey/questions/answer/listradio/config.xml#L48-L253

**Comment by Shnoulle** [comment]
@tpartner testing this version in 5.X and 6.X : it work on both

- 6.X use `attributes` and **don't care** of `custom_attributes`
- 5.X use `custom_attributes` **and don't care** of `attributes`

**Comment by tpartner** [comment]
Thanks @Shnoulle. Also tested in 3.x.

**Pull request merged**
